general {
    lock_cmd = loginctl lock-session                   # lock screen
    before_sleep_cmd = loginctl lock-session            # lock before suspend
    after_sleep_cmd = sleep 1 && hyprctl dispatch dpms on
    inhibit_sleep = 3                                   # wait until screen is locked
}

listener {
    timeout = 150
    on-timeout = pidof hyprlock || hyprlock
}

listener {
    timeout = 152
    on-timeout = loginctl lock-session
    on-resume = hyprctl dispatch dpms on
}
