{ colors }:
''
-- Gum Style (generic) Variables
hl.env("FOREGROUND", "${colors.foreground}")
hl.env("BACKGROUND", "${colors.background}")
hl.env("BORDER_FOREGROUND", "${colors.accent}")
hl.env("BORDER_BACKGROUND", "${colors.background}")

-- Gum Confirm Style Variables
hl.env("GUM_CONFIRM_PROMPT_FOREGROUND", "${colors.accent}")
hl.env("GUM_CONFIRM_PROMPT_BACKGROUND", "${colors.background}")
hl.env("GUM_CONFIRM_SELECTED_FOREGROUND", "${colors.selection_foreground}")
hl.env("GUM_CONFIRM_SELECTED_BACKGROUND", "${colors.selection_background}")
hl.env("GUM_CONFIRM_UNSELECTED_FOREGROUND", "${colors.foreground}")
hl.env("GUM_CONFIRM_UNSELECTED_BACKGROUND", "${colors.background}")

-- Gum Input Style Variables
hl.env("GUM_INPUT_PROMPT_FOREGROUND", "${colors.accent}")
hl.env("GUM_INPUT_PROMPT_BACKGROUND", "${colors.background}")
hl.env("GUM_INPUT_PLACEHOLDER_FOREGROUND", "${colors.color8}")
hl.env("GUM_INPUT_PLACEHOLDER_BACKGROUND", "${colors.background}")
hl.env("GUM_INPUT_CURSOR_FOREGROUND", "${colors.cursor}")
hl.env("GUM_INPUT_CURSOR_BACKGROUND", "${colors.background}")
hl.env("GUM_INPUT_HEADER_FOREGROUND", "${colors.foreground}")
hl.env("GUM_INPUT_HEADER_BACKGROUND", "${colors.background}")

-- Gum Choose Style Variables
hl.env("GUM_CHOOSE_CURSOR_FOREGROUND", "${colors.accent}")
hl.env("GUM_CHOOSE_CURSOR_BACKGROUND", "${colors.background}")
hl.env("GUM_CHOOSE_HEADER_FOREGROUND", "${colors.foreground}")
hl.env("GUM_CHOOSE_HEADER_BACKGROUND", "${colors.background}")
hl.env("GUM_CHOOSE_ITEM_FOREGROUND", "${colors.foreground}")
hl.env("GUM_CHOOSE_ITEM_BACKGROUND", "${colors.background}")
hl.env("GUM_CHOOSE_SELECTED_FOREGROUND", "${colors.selection_foreground}")
hl.env("GUM_CHOOSE_SELECTED_BACKGROUND", "${colors.selection_background}")

-- Gum Filter Style Variables
hl.env("GUM_FILTER_PROMPT_FOREGROUND", "${colors.accent}")
hl.env("GUM_FILTER_PROMPT_BACKGROUND", "${colors.background}")
hl.env("GUM_FILTER_TEXT_FOREGROUND", "${colors.foreground}")
hl.env("GUM_FILTER_TEXT_BACKGROUND", "${colors.background}")
hl.env("GUM_FILTER_MATCH_FOREGROUND", "${colors.accent}")
hl.env("GUM_FILTER_CURSOR_TEXT_FOREGROUND", "${colors.cursor}")
hl.env("GUM_FILTER_CURSOR_TEXT_BACKGROUND", "${colors.background}")
hl.env("GUM_FILTER_SELECTED_FOREGROUND", "${colors.selection_foreground}")
hl.env("GUM_FILTER_SELECTED_BACKGROUND", "${colors.selection_background}")
hl.env("GUM_FILTER_INDICATOR_FOREGROUND", "${colors.accent}")
hl.env("GUM_FILTER_HEADER_FOREGROUND", "${colors.foreground}")
hl.env("GUM_FILTER_MATCH_BACKGROUND", "${colors.background}")
hl.env("GUM_FILTER_HEADER_BACKGROUND", "${colors.background}")
hl.env("GUM_FILTER_PLACEHOLDER_FOREGROUND", "${colors.color8}")
hl.env("GUM_FILTER_PLACEHOLDER_BACKGROUND", "${colors.background}")
hl.env("GUM_FILTER_INDICATOR_BACKGROUND", "${colors.background}")
hl.env("GUM_FILTER_SELECTED_PREFIX_FOREGROUND", "${colors.selection_foreground}")
hl.env("GUM_FILTER_SELECTED_PREFIX_BACKGROUND", "${colors.selection_background}")
hl.env("GUM_FILTER_UNSELECTED_PREFIX_FOREGROUND", "${colors.color8}")
hl.env("GUM_FILTER_UNSELECTED_PREFIX_BACKGROUND", "${colors.background}")

-- Gum Table Style Variables
hl.env("GUM_TABLE_HEADER_FOREGROUND", "${colors.foreground}")
hl.env("GUM_TABLE_HEADER_BACKGROUND", "${colors.background}")
hl.env("GUM_TABLE_CELL_FOREGROUND", "${colors.foreground}")
hl.env("GUM_TABLE_CELL_BACKGROUND", "${colors.background}")
hl.env("GUM_TABLE_BORDER_FOREGROUND", "${colors.color8}")
hl.env("GUM_TABLE_BORDER_BACKGROUND", "${colors.background}")
hl.env("GUM_TABLE_SELECTED_FOREGROUND", "${colors.selection_foreground}")
hl.env("GUM_TABLE_SELECTED_BACKGROUND", "${colors.selection_background}")

-- Gum Spin Style Variables
hl.env("GUM_SPIN_SPINNER_FOREGROUND", "${colors.accent}")
hl.env("GUM_SPIN_SPINNER_BACKGROUND", "${colors.background}")
hl.env("GUM_SPIN_TITLE_FOREGROUND", "${colors.foreground}")
hl.env("GUM_SPIN_TITLE_BACKGROUND", "${colors.background}")

-- Gum File Style Variables
hl.env("GUM_FILE_CURSOR_FOREGROUND", "${colors.cursor}")
hl.env("GUM_FILE_CURSOR_BACKGROUND", "${colors.background}")
hl.env("GUM_FILE_SYMLINK_FOREGROUND", "${colors.foreground}")
hl.env("GUM_FILE_SYMLINK_BACKGROUND", "${colors.background}")
hl.env("GUM_FILE_DIRECTORY_FOREGROUND", "${colors.foreground}")
hl.env("GUM_FILE_DIRECTORY_BACKGROUND", "${colors.background}")
hl.env("GUM_FILE_FILE_FOREGROUND", "${colors.foreground}")
hl.env("GUM_FILE_FILE_BACKGROUND", "${colors.background}")
hl.env("GUM_FILE_PERMISSIONS_FOREGROUND", "${colors.color8}")
hl.env("GUM_FILE_PERMISSIONS_BACKGROUND", "${colors.background}")
hl.env("GUM_FILE_SELECTED_FOREGROUND", "${colors.selection_foreground}")
hl.env("GUM_FILE_SELECTED_BACKGROUND", "${colors.selection_background}")
hl.env("GUM_FILE_FILE_SIZE_FOREGROUND", "${colors.color8}")
hl.env("GUM_FILE_FILE_SIZE_BACKGROUND", "${colors.background}")
hl.env("GUM_FILE_HEADER_FOREGROUND", "${colors.foreground}")
hl.env("GUM_FILE_HEADER_BACKGROUND", "${colors.background}")

-- Gum Pager Style Variables
hl.env("GUM_PAGER_FOREGROUND", "${colors.foreground}")
hl.env("GUM_PAGER_BACKGROUND", "${colors.background}")
hl.env("GUM_PAGER_LINE_NUMBER_FOREGROUND", "${colors.color8}")
hl.env("GUM_PAGER_LINE_NUMBER_BACKGROUND", "${colors.background}")
hl.env("GUM_PAGER_MATCH_FOREGROUND", "${colors.accent}")
hl.env("GUM_PAGER_MATCH_BACKGROUND", "${colors.background}")
hl.env("GUM_PAGER_MATCH_HIGH_FOREGROUND", "${colors.accent}")
hl.env("GUM_PAGER_MATCH_HIGH_BACKGROUND", "${colors.background}")
hl.env("GUM_PAGER_HELP_FOREGROUND", "${colors.color8}")
hl.env("GUM_PAGER_HELP_BACKGROUND", "${colors.background}")

-- Gum Write Style Variables
hl.env("GUM_WRITE_BASE_FOREGROUND", "${colors.foreground}")
hl.env("GUM_WRITE_BASE_BACKGROUND", "${colors.background}")
hl.env("GUM_WRITE_CURSOR_LINE_NUMBER_FOREGROUND", "${colors.color8}")
hl.env("GUM_WRITE_CURSOR_LINE_NUMBER_BACKGROUND", "${colors.background}")
hl.env("GUM_WRITE_CURSOR_LINE_FOREGROUND", "${colors.foreground}")
hl.env("GUM_WRITE_CURSOR_LINE_BACKGROUND", "${colors.selection_background}")
hl.env("GUM_WRITE_CURSOR_FOREGROUND", "${colors.cursor}")
hl.env("GUM_WRITE_CURSOR_BACKGROUND", "${colors.background}")
hl.env("GUM_WRITE_END_OF_BUFFER_FOREGROUND", "${colors.color8}")
hl.env("GUM_WRITE_END_OF_BUFFER_BACKGROUND", "${colors.background}")
hl.env("GUM_WRITE_LINE_NUMBER_FOREGROUND", "${colors.color8}")
hl.env("GUM_WRITE_LINE_NUMBER_BACKGROUND", "${colors.background}")
hl.env("GUM_WRITE_HEADER_FOREGROUND", "${colors.foreground}")
hl.env("GUM_WRITE_HEADER_BACKGROUND", "${colors.background}")
hl.env("GUM_WRITE_PLACEHOLDER_FOREGROUND", "${colors.color8}")
hl.env("GUM_WRITE_PLACEHOLDER_BACKGROUND", "${colors.background}")
hl.env("GUM_WRITE_PROMPT_FOREGROUND", "${colors.foreground}")
hl.env("GUM_WRITE_PROMPT_BACKGROUND", "${colors.background}")

-- Gum Log Style Variables
hl.env("GUM_LOG_LEVEL_FOREGROUND", "${colors.accent}")
hl.env("GUM_LOG_LEVEL_BACKGROUND", "${colors.background}")
hl.env("GUM_LOG_TIME_FOREGROUND", "${colors.color8}")
hl.env("GUM_LOG_TIME_BACKGROUND", "${colors.background}")
hl.env("GUM_LOG_PREFIX_FOREGROUND", "${colors.foreground}")
hl.env("GUM_LOG_PREFIX_BACKGROUND", "${colors.background}")
hl.env("GUM_LOG_MESSAGE_FOREGROUND", "${colors.foreground}")
hl.env("GUM_LOG_MESSAGE_BACKGROUND", "${colors.background}")
hl.env("GUM_LOG_KEY_FOREGROUND", "${colors.foreground}")
hl.env("GUM_LOG_KEY_BACKGROUND", "${colors.background}")
hl.env("GUM_LOG_VALUE_FOREGROUND", "${colors.foreground}")
hl.env("GUM_LOG_VALUE_BACKGROUND", "${colors.background}")
hl.env("GUM_LOG_SEPARATOR_FOREGROUND", "${colors.color8}")
hl.env("GUM_LOG_SEPARATOR_BACKGROUND", "${colors.background}")
''
