name: conventional-pr

on:
  pull_request:
    types: [opened, edited, synchronize]
    branches:
      - main

jobs:
  lint:
    runs-on: ubuntu-latest
    steps:
      - uses: CondeNast/conventional-pull-request-action@24f2af2b7f223b255eb93f3ec4ecec97b3a6dbb0 # v0.5.0
        with:
          ignoreCommits: true
        env:
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
