name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@7987652d0c02f4b64f7e4ca37c5828a7faf61927 # v4.1.5
        with:
          release-type: simple
