name: release-please

on:
  push:
    branches:
      - main

permissions:
  contents: write
  pull-requests: write

jobs:
  release-please:
    runs-on: ubuntu-latest
    steps:
      - uses: googleapis/release-please-action@fa6912186f981cf2712e7fdff20c78402a2d2491 # v4.4.1
        with:
          release-type: simple
